# ==========================================
# CONFIGURACIÓN RENDER - DOCKER DEPLOY
# ==========================================

services:
  # Backend Service
  - type: web
    name: techstore-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /api/salud
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: DATABASE_URL
        value: sqlite:///./inventario.db
      - key: ENVIRONMENT
        value: production
