services:
  # Backend API
  - type: web
    name: techstore-backend
    env: python
    plan: free
    buildCommand: "chmod +x build_render.sh && ./build_render.sh"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///./inventario.db"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"
      - key: ENVIRONMENT
        value: "production"
